services:
  qdrant:
    healthcheck:
      test: ["CMD-SHELL", "bash -lc 'exec 3<>/dev/tcp/127.0.0.1/6333; printf \"GET /readyz HTTP/1.1\\r\\nHost: localhost\\r\\n\\r\\n\" >&3; head -n1 <&3 | grep -q \"200\"'"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
  litellm:
    healthcheck:
      test: ["CMD-SHELL", "bash -lc 'exec 3<>/dev/tcp/127.0.0.1/4000; printf \"GET /v1/models HTTP/1.1\\r\\nHost: localhost\\r\\n\\r\\n\" >&3; head -n1 <&3 | grep -q \"200\"'"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s
  openwebui:
    healthcheck:
      test: ["CMD-SHELL", "bash -lc 'exec 3<>/dev/tcp/127.0.0.1/8080; printf \"GET / HTTP/1.1\\r\\nHost: localhost\\r\\n\\r\\n\" >&3; head -n1 <&3 | grep -q \"200\"'"]
      interval: 15s
      timeout: 3s
      retries: 10
      start_period: 10s
