---
name: Compose Config

on:
  push:
  pull_request:

jobs:
  compose-config:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker info
        run: |
          docker version
          docker compose version

      - name: Validate docker compose config
        working-directory: ai_gateway
        run: |
          set -euo pipefail
          docker compose -f docker-compose.stack.yml -f docker-compose.pins.yml -f docker-compose.health.yml config
