name: Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yamllint and shellcheck
        run: |
          sudo apt-get update -y
          sudo apt-get install -y yamllint shellcheck

      - name: Run yamllint (repo root)
        run: |
          set -e
          yamllint -s .

      - name: Run shellcheck (tracked .sh)
        run: |
          set -e
          files=$(git ls-files '**/*.sh' | grep -Ev '^(_archive/|_logs/|vendor/)') || true
          if [ -n "$files" ]; then
            shellcheck -x $files
          else
            echo "No shell scripts to lint."
          fi
