---
name: Lint

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yamllint and shellcheck
        run: |
          sudo apt-get update -y
          sudo apt-get install -y yamllint shellcheck

      - name: Run yamllint (workflows + core compose)
        run: |
          set -e
          files=$(git ls-files \
            '.github/workflows/*.yml' \
            'ai_gateway/docker-compose.stack.yml' \
            'ai_gateway/docker-compose.pins.yml' \
            'ai_gateway/docker-compose.health.yml' \
            'ai_gateway/config/*.yaml' \
          ) || true
          if [ -n "$files" ]; then
            yamllint -s $files
          else
            echo "No YAML files to lint."
          fi

      - name: Run shellcheck (ai_gateway scripts)
        run: |
          set -e
          files=$(git ls-files 'ai_gateway/**/*.sh') || true
          if [ -n "$files" ]; then
            shellcheck -x $files
          else
            echo "No ai_gateway shell scripts to lint."
          fi

      - name: Run shellcheck (tracked .sh)
        run: |
          set -e
          files=$(git ls-files '**/*.sh' | grep -Ev '^(_archive/|_logs/|vendor/|_labs/|scripts/)') || true
          if [ -n "$files" ]; then
            shellcheck -x $files
          else
            echo "No shell scripts to lint."
          fi
