---
name: Secrets

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install gitleaks
        run: |
          set -euo pipefail
          curl -sSL https://raw.githubusercontent.com/gitleaks/gitleaks/master/install.sh | sudo bash
          gitleaks version

      - id: scan
        name: Run gitleaks (exclude _archive/_logs)
        run: |
          set +e
          gitleaks detect \
            --source . \
            --no-git \
            --redact \
            --exclude-paths "_archive/**,_logs/**" \
            --report-format sarif \
            --report-path gitleaks.sarif \
            --exit-code 1
          code=$?
          set -e
          echo "code=$code" >> "$GITHUB_OUTPUT"

      - name: Upload report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks.sarif

      - name: Fail on findings
        if: steps.scan.outputs.code != '0'
        run: |
          echo "Gitleaks detected potential secrets. See gitleaks-report artifact." >&2
          exit 1
