---
name: Smoke

on:
  workflow_dispatch:
  pull_request:
    types: [labeled]

jobs:
  smoke:
    # Run when manually dispatched, or when PR gets label 'smoke'
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'smoke')
    runs-on: ubuntu-latest
    timeout-minutes: 60
    services:
      docker:
        image: docker:24-dind
        options: >-
          --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""
    env:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_TLS_CERTDIR: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Wait for Docker
        run: |
          for i in $(seq 1 60); do
            docker version && break || sleep 2
          done
          docker info
          docker compose version

      - name: Ensure external network exists
        run: |
          docker network create ai_stack_net || true

      - name: Compose up
        working-directory: ai_gateway
        run: |
          cp .env.example .env
          docker compose -f docker-compose.stack.yml -f docker-compose.pins.yml -f docker-compose.health.yml up -d

      - name: Wait for health
        working-directory: ai_gateway
        run: |
          ./WAIT_HEALTH.sh

      - name: Smoke tests
        working-directory: ai_gateway
        run: |
          ./SMOKE_NOW.sh

      - name: Compose ps
        if: always()
        working-directory: ai_gateway
        run: docker compose -f docker-compose.stack.yml -f docker-compose.pins.yml -f docker-compose.health.yml ps

      - name: Compose logs (last 200)
        if: always()
        working-directory: ai_gateway
        run: docker compose -f docker-compose.stack.yml -f docker-compose.pins.yml -f docker-compose.health.yml logs --tail=200

      - name: Collect logs on failure
        if: failure()
        working-directory: ai_gateway
        run: |
          set -euo pipefail
          mkdir -p ../_gha_artifacts
          docker compose -f docker-compose.stack.yml -f docker-compose.pins.yml -f docker-compose.health.yml ps > ../_gha_artifacts/compose_ps.txt || true
          docker compose -f docker-compose.stack.yml -f docker-compose.pins.yml -f docker-compose.health.yml logs --no-color > ../_gha_artifacts/compose_logs.txt || true

      - name: Upload logs artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-logs
          path: _gha_artifacts

      - name: Compose down
        if: always()
        working-directory: ai_gateway
        run: docker compose -f docker-compose.stack.yml -f docker-compose.pins.yml -f docker-compose.health.yml down -v
